name: devexam
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # To change language of app.
  easy_localization: ^3.0.0

  # To upload user data to firebase cloud.
  cloud_firestore: ^1.0.0 #^0.16.0

  # To authenticate 
  firebase_auth: ^1.0.0 #^0.20.0+1

  # To manage firebase easily
  firebase_core: ^1.0.0 #^0.7.0

  # To upload profile picture
  firebase_storage: ^8.0.0 #^7.0.0

  # To make complex dart class
  equatable: ^1.2.5
  meta: ^1.2.4
  formz: ^0.3.2

  # To save data localy
  shared_preferences: ^2.0.3

  # To manage complex state.
  flutter_bloc: ^6.1.1

  # To open photos of questions
  photo_view: ^0.10.3

  # To fetch image from internet without problem
  cached_network_image: #^2.5.0

  # To upload image as a profile picture - crop image
  image_picker: ^0.7.2 #^0.6.7+22
  image_cropper: ^1.3.1
  permission_handler: ^6.0.1 #^5.1.0+2

  # For UI.
  flutter_spinkit:

  # Icons
  cupertino_icons: ^0.1.3

  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:

  # Custom Images (icon, logo, image)
    - assets/custom/exam.png
    - assets/custom/test.png
    - assets/custom/good.png
    - assets/custom/better.png
    - assets/custom/bad.png
    - assets/custom/empty.png
    - assets/custom/logo.png
    - assets/custom/wifi.png
    - assets/custom/wifi_white.png

    # Images of jsons (Question images)
    - assets/img/none.png
    - assets/img/9.png
    - assets/img/11.png

    # Json Files 
    - assets/languages/en.json
    - assets/languages/ru.json
    - assets/json/en.json
    - assets/json/ru.json
