name: build-ios

# This workflow is triggered on pull requests and pushes to the repository.
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:
  build:
    name: Build the application for iOS

    # This job will run on Ubuntu virtual machine.
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Setup the Flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # "alpha", "beta", "dev", default to: "stable"
          #
          # # You can also specify exact version of Flutter.
          flutter-version: "2.0.1"

      - name: Build iOS
        run: flutter build ios --release --no-codesign
